bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '10000':'₹10,000',
  '20000':'₹20,000',
  '30000':'₹30,000',
  '40000':'₹40,000',
  '50000':'₹50,000',
  '60000':'₹60,000',
  '70000':'₹70,000',
  '80000':'₹80,000',
  '90000':'₹90,000',
  '100000':'₹100,000',
}

state_choices = {
        'AP': 'Andhra Pradesh',
        'AR': 'Arunachal Pradesh',
        'AS': 'Assam',
        'BR': 'Bihar',
        'CT': 'Chhattisgarh',
        'GA': 'Goa',
        'GJ': 'Gujarat',
        'HR': 'Haryana',
        'HP': 'Himachal Pradesh',
        'JK': 'Jammu and Kashmir',
        'JH': 'Jharkhand',
        'KA': 'Karnataka',
        'KL': 'Kerala',
        'MP': 'Madhya Pradesh',
        'MH': 'Maharashtra',
        'MN': 'Manipur',
        'ML': 'Meghalaya',
        'MZ': 'Mizoram',
        'NL': 'Nagaland',
        'OR': 'Odisha',
        'PB': 'Punjab',
        'RJ': 'Rajasthan',
        'SK': 'Sikkim',
        'TN': 'Tamil Nadu',
        'TG': 'Telangana',
        'TR': 'Tripura',
        'UT': 'Uttarakhand',
        'UP': 'Uttar Pradesh',
        'WB': 'West Bengal',
        'AN': 'Andaman and Nicobar Islands',
        'CH': 'Chandigarh',
        'DN': 'Dadra and Nagar Haveli',
        'DD': 'Daman and Diu',
        'DL': 'Delhi',
        'LD': 'Lakshadweep',
        'PY':'Puducherry',
}